backend:
  name: github
  repo: gustxsw/nexure-cms
  branch: main
  base_url: https://decap-gateway.netlify.app
  auth_endpoint: /api/auth
  app_id: Ov23liJP0b0tXqjcMTfz

media_folder: "images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Página Inicial"
    files:
      - file: "content/home.md"
        label: "Conteúdo da Home"
        name: "home"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subheadline", name: "subheadline", widget: "string" }
          - {
              label: "Benefícios",
              name: "benefits",
              widget: "list",
              field: { label: "Texto", name: "benefit", widget: "string" },
            }
          - label: "Planos"
            name: "planos"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "string" }
