backend:
  name: github
  repo: gustxsw/nexure-cms # seu repositório
  branch: main
  auth_type: oauth
  app_id: Ov23liJP0b0tXqjcMTfz
  base_url: https://coruscating-belekoy-9e312a.netlify.app
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "/images"
